import {useRouter} from "next/router";
import React from "react";
import {MainLayout} from "../../components/layout/MainLayout";
import {useAppSelector} from "../../hooks/useAppSelector";
import Head from "next/head";
import Image from "next/image";

interface GamePageProps {

}

const GamePage: React.FC<GamePageProps> = () => {
    const {games} = useAppSelector(state => state.games)

    const router = useRouter()
    const {game} = router.query

    let name = games[String(game)]?.name || "name"
    let img = games[String(game)]?.image || "img"
    let description = games[String(game)]?.description || "description"
    let levels = games[String(game)]?.levels || []

    return <div>
        <Head>
            <title>sdfsds</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <MainLayout>
            <div className={"p-3"}>
                <div className="flex">
                    <div className="overflow-hidden w-32 h-32">
                        <Image className="object-fill rounded-2xl" src={img}/>
                    </div>
                    <div className={"p-2"}>
                        <h1 className="text-3xl font-bold text-gray-900">{name}</h1>
                        <p>{description}</p>
                    </div>
                </div>

                {
                    Object.keys(levels).map(el => {
                        return <div key={el} className={"border rounded-l m-0.5 p-1"}>
                            Вопрос: {levels[el].question} <br/>
                            Ответ: {levels[el].answer} <br/>
                        </div>
                    })
                }

            </div>

        </MainLayout>
    </div>
}

export default GamePage

