import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useSelector} from "react-redux";
import {RootState} from "../store";

const Home: NextPage = () => {
    let { games } = useSelector((state: RootState) => state.games)
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <div>
                { Object.keys(games).map(game => {
                    return <h1 key={game} className="text-3xl font-bold underline">{games[game].name}</h1>
                })}
            </div>
        </div>
    )
}

export default Home
